### ISSUE TITLE
Nueva font

### ISSUE THREAD

**Issue by neclord02** [GrupoDGP/heisenburg#1]
Buscar una font para nuestro diseño de la web (los titulos h1 h2...)

**Comment by neclord02** [comment]
Que tal esta: http://www.ffonts.net/headplane.font

**Comment by angrykoala** [comment]
No se si es buena idea usar fonts raras, creo que el visitante tendría que tenerla instalada, si es para ttitulos mejor una imagen y ya esta

**Comment by angrykoala** [comment]
En caso de que se pueda almacenar en la web el font para que cualquiera pueda leerlo, aqui hay una pilaca de fonts libres: http://openfontlibrary.org/es

**Comment by neclord02** [comment]
Nueva font puesta, menos "tecnologica"
